name: Publish package on registry

on:
  release:
    types:
      - published

concurrency:
  group: publish-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  publish:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Publish to JSR
        run: bunx --bun jsr publish

      - name: Publish to npm
        # env:
        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun publish --access public